### ISSUE TITLE
Nice application

### ISSUE THREAD

**Issue by jayeshcp** [shihjay2/nosh-core#1]
Is this project in current development ? I would like to contribute in the development and enhancements if any.

**Comment by shihjay2** [comment]
Jayesh,

Thanks for your interest!   Yes, this project is in current development.
I'm currently working on an API framework based on FHIR standards so right
now it's not in the master branch yet.  Let me know what your
interest/ideas/contributions would be and we can discuss.

Michael Chen, MD

**Comment by jayeshcp** [comment]
I have good working knowledge of laravel, jquery, angularjs and other web technologies. I also have experience working on EMR products.

I can start with small enhancements or bugs that needs to be fixed. I am open to your suggestions.
In the mean time, I will play around with the application and get acquainted with it.
