### ISSUE TITLE
Create patient using API

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh-core#2]
Is there a way to create a patient using API? I am working on single sign-on for patient between multiple applications. As my front portal is in Yii, I want to create a user in nosh too when I create a user in Yii.

Can you let me know how we can do this?

**Comment by shihjay2** [comment]
At this point there is no API for creating a patient in NOSH.  There may be
in the future and if that happens it will follow the FHIR specifications
that is being developed and tested right now.

Michael
